#!/usr/bin/env sh

jump() {
  prefix=$(npm prefix -g)
  output="$($prefix/bin/jumpy $@)"
  first="${output:0:1}"
  rest="${output:1}"

  if [[ "$first" == "%" ]]; then
   cd "$rest"
  elif [[ "$first" == "$" ]]; then
    ssh "$rest"
  else
    echo "$output"
  fi
}
